# Generated by Django 5.0.4 on 2024-05-05 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_uid', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('discount_info', models.CharField(blank=True, max_length=100)),
                ('description_filter_html', models.TextField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('web_sales', models.URLField(blank=True)),
                ('source_web_promote', models.URLField(blank=True)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('edit_modify_date', models.DateTimeField(blank=True)),
                ('hit_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceWebName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Show.country')),
            ],
        ),
        migrations.CreateModel(
            name='MasterUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Show.showinfo', to_field='show_uid')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Show.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('on_sales', models.BooleanField()),
                ('price', models.CharField(blank=True, max_length=100)),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Show.location')),
                ('show_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showTime', to='Show.showinfo', to_field='show_uid')),
            ],
        ),
        migrations.CreateModel(
            name='ShowUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Show.performer')),
                ('show_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Show.showinfo', to_field='show_uid')),
            ],
        ),
        migrations.AddField(
            model_name='showinfo',
            name='source_web_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Show.sourcewebname'),
        ),
        migrations.CreateModel(
            name='OtherUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Show.showinfo', to_field='show_uid')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Show.tag')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Show.unit')),
            ],
        ),
        migrations.CreateModel(
            name='SupportUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Show.showinfo', to_field='show_uid')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Show.unit')),
            ],
        ),
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Show.showinfo', to_field='show_uid')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Show.unit')),
            ],
        ),
        migrations.AddField(
            model_name='showinfo',
            name='master_unit',
            field=models.ManyToManyField(through='Show.MasterUnit', to='Show.unit'),
        ),
        migrations.AddField(
            model_name='showinfo',
            name='other_unit',
            field=models.ManyToManyField(related_name='other_show', through='Show.OtherUnit', to='Show.unit'),
        ),
        migrations.AddField(
            model_name='showinfo',
            name='sub_unit',
            field=models.ManyToManyField(related_name='sub_show', through='Show.SubUnit', to='Show.unit'),
        ),
        migrations.AddField(
            model_name='showinfo',
            name='support_unit',
            field=models.ManyToManyField(related_name='support_show', through='Show.SupportUnit', to='Show.unit'),
        ),
    ]
