# Generated by Django 5.0.4 on 2024-05-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinfo',
            name='show_unit',
            field=models.ManyToManyField(through='Show.ShowUnit', to='Show.performer'),
        ),
        migrations.AlterField(
            model_name='showinfo',
            name='edit_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
