# Generated by Django 5.0.4 on 2024-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0002_showinfo_show_unit_alter_showinfo_edit_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showinfo',
            name='hit_rate',
            field=models.IntegerField(auto_created=0),
        ),
    ]
