# Generated by Django 5.0.4 on 2024-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0003_alter_showinfo_hit_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showinfo',
            name='hit_rate',
            field=models.IntegerField(auto_created=True),
        ),
    ]
